Feature. Apply Styles to TDataGrid and TPagination, Modify Test Code
openinfradev/tksui-components pull request #25
Opened 2024-01-22 05:58 UTC by kkusaeng

- Add jumper in TPagination 🏃🏻‍♂️
- Apply DataGrid, Pagination style 💃🏻
- Modify TPagination and TDataGrid test code 🧑🏻‍💻

2024-01-22 07:49 UTC, Siyeop commented on src/components/data-container/data-grid/TDataGrid.tsx
> +                <path transform="translate(49 62.953)" style={{fill: '#999'}} d="M0 0h4v4H0z"/>
포매터 설정이 약간 저랑 다른 느낌인데요?

2024-01-22 08:01 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
>                         onKeyDownSpace={onClickNextPageSet}>t_navigate_right_double</TIcon>
아이콘 교체 부탁드립니다.
- t_navigate_right -> keyboard_arrow_right
- t_navigate_right_double -> keyboard_double_arrow_right
- t_navigate_left -> keyboard_arrow_left
- t_navigate_left_double -> keyboard_double_arrow_left

2024-01-22 08:01 UTC, Siyeop commented on src/styles/component/data-container/data-grid/TDataGrid.scss
> +        //height: 46px;
필요없는거는 주석보다 그냥 지워주세요

2024-01-22 08:02 UTC, Siyeop commented on src/styles/component/data-container/data-grid/TDataGrid.scss
> +        --ag-font-size: var(--t-font-size-large);
ag-grid 공식문서에서

size, font-weight, line-height 관련된 변수 3개를 모두 찾아서 셋다 고쳐놓으면 더 좋을 것 같습니다.

2024-01-22 08:04 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
> +                            {props.jumperText ? props.jumperText : '바로가기'}
defaultProps 로 빼면 좋을 것 같아요.

2024-01-22 08:05 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
> +                            {props.jumperText ? props.jumperText : '바로가기'}
boolean을 jumper 로 주는 것보다, 
noJumper 로 해서 noJumper 인 경우에 날리는 편이 더 좋을 것 같습니다.

2024-01-22 08:07 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
> +                            {props.jumperText ? props.jumperText : '바로가기'}
스토리북에서 보면 값 입력이 잘 안되는데, 확인 부탁드립니다.

NumberField 오류 같으면 이야기 해주세요. 같이 보겠습니다.

![image](https://github.com/openinfradev/tksui-components/assets/62166127/86db5996-b971-4dfd-8350-511c07c10648)

2024-01-22 08:11 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
> +    const [jumpPage, setJumpPage] = useState<number>(props.pageNumber);
사용여부를 나타내는 prop을 jumper 로 했으니, 
단어를 맞춰서 jumperPage 로 하는 것이 좋을 것 같네요

2024-01-22 08:14 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
> +    }, [jumpPage, pageRange, onChangePageNumber]);
jumper 는 2개의 요소를 갖고 있는데요.
- 값 입력부분: jumperValue
- 버튼: jumperButton 

이런 식으로 구체적인 네이밍을 해주는 것이 좋겠습니다.
onClickJumper 라고 하면, 둘 중 하나라도 클릭하면 발생하는 이벤트처럼 보입니다.

2024-01-22 08:18 UTC, Siyeop commented on src/styles/component/data-container/pagination/TPagination.scss
> +            @include typo-element-4;
클래스 명이 잘 이해가 안되긴 하네요.

jumper 아래에 container가 있고,

그 아래 page와 short-cut 이 있는건가요?
short-cut 아래에 button 이 왜 있어야 하는건지 잘 이해가 안됩니다.

container 아래 바로 number field 와 button이 오면 될 것 같아서요.
아마도 short-cut 이라는 놈이 초반 구현에는 있었다가 중간에 빠진 느낌이네요

2024-01-22 08:22 UTC, Siyeop commented on src/components/data-container/pagination/TPagination.tsx
>      }));
useImperativeHandle 에 jumpToPage 하나 추가하면 좋을 것 같습니다.

지금 내가 하는 리뷰들이 스타일 수정의 범주에 들어가는게 맞긴 한가 싶은 생각이 들기 시작했습니다.

2024-01-22 08:23 UTC, Siyeop requested changes
수정 후에 이야기 해주세요.
jumper 가 제대로 작동하지 않는 문제때문에 
다시 한 번 보고 머지하는 것이 안전할 것 같습니다.

고생 많으셨습니다. 👍

2024-01-22 08:30 UTC, kkusaeng commented on src/components/data-container/data-grid/TDataGrid.tsx
> +                <path transform="translate(49 62.953)" style={{fill: '#999'}} d="M0 0h4v4H0z"/>
포멧터는 같은데 이상하게 자동으로 변환이 안되네요 🤯

2024-01-22 08:48 UTC, kkusaeng commented on src/styles/component/data-container/data-grid/TDataGrid.scss
> +        --ag-font-size: var(--t-font-size-large);
[ag-grid Docs](https://www.ag-grid.com/javascript-data-grid/global-style-customisation-colours/)

```
.ag-theme-quartz {
    --ag-foreground-color: rgb(126, 46, 132);
    --ag-background-color: rgb(249, 245, 227);
    --ag-header-foreground-color: rgb(204, 245, 172);
    --ag-header-background-color: rgb(209, 64, 129);
    --ag-odd-row-background-color: rgb(0, 0, 0, 0.03);
    --ag-header-column-resize-handle-color: rgb(126, 46, 132);

    --ag-font-size: 17px;
    --ag-font-family: monospace;
}
```

공식 문서에 폰트 사이즈와 패밀리 정도만 나와있고 `line-height`과 `weight`는 없더라구요. 개발자 도구로 살펴보니 `line-height`의 경우 `TDataGrid` `prop` 중 `rowHeight`값이 자동 계산되어 하위 모든 요소에 들어가더라구요. `font-weight` 정도만 `.ag-cell` 클래스에 넣는게 어떨까요?

2024-01-22 08:54 UTC, kkusaeng commented on src/components/data-container/pagination/TPagination.tsx
> +    const [jumpPage, setJumpPage] = useState<number>(props.pageNumber);
exactly합니다! 👍

2024-01-22 09:08 UTC, Siyeop commented on src/styles/component/data-container/data-grid/TDataGrid.scss
> +        --ag-font-size: var(--t-font-size-large);
1. ag grid 에서 공식적인 확장 포인트를 제공하지 않고,
2. override 하지 않더라도
동일한 모양이 나온다면 굳이 override 하지 않아도 될 것 같습니다.

2024-01-22 09:27 UTC, kkusaeng commented on src/styles/component/data-container/data-grid/TDataGrid.scss
> +        --ag-font-size: var(--t-font-size-large);
넵 마침 `font-weight: 400;` 이라 속성을 주지 않아도 동일합니당! 🕺🏻

2024-01-22 10:05 UTC, kkusaeng commented on src/components/data-container/pagination/TPagination.tsx
> +                            {props.jumperText ? props.jumperText : '바로가기'}
기능 오류도 수정했습니다! 🔥 🔥 🔥 🔥 🔥

2024-01-22 10:36 UTC, kkusaeng commented on src/styles/component/data-container/pagination/TPagination.scss
> +            @include typo-element-4;
'바로가기'에 꽂혀서 `short-cut`으로 했는데, 시엽님 말씀대로 `onClickJumperButton` 처럼 `Jumper__container__button` 으로 통일하면 좋은 것 같습니다. 👍👍👍

2024-01-23 01:25 UTC, Siyeop commented on src/components/data-container/data-grid/TDataGrid.tsx
>                              )
뒤늦게 미안하지만, 여기도 TActionBar로 교체해 볼까요?

2024-01-23 03:13 UTC, Siyeop approved these changes
리뷰 다 처리해주시느라 고생 많으셨습니다.

pagination의 숫자 입력 validation 관련 내용은 별도 이슈로 등록하고 
이 PR은 여기까지하고 머지하는게 좋을 것 같습니다.

2024-01-23 03:59 UTC, kkusaeng commented on src/components/data-container/data-grid/TDataGrid.tsx
>                              )
아닙니당~ 바로 처리하죠

2024-01-23 04:23 UTC, merged