feature. Modify TToast Styles
openinfradev/tksui-components pull request #35
Opened 2024-01-29 06:39 UTC by TaekRyeol

# Key Changes of PR
- Modify TToast Styles

# Screenshots
![image](https://github.com/openinfradev/tksui-components/assets/154313468/17cdce18-b63e-49ae-94f0-8dfc8958401a)

2024-01-30 09:09 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +            top: 4em;
음 여기는 왜 em 단위를 사용하셨나요?
어차피 상대단위를 안쓰고 있어서 px 로 해도 괜찮을 것 같은데요.

2024-01-30 09:09 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +            top: 4em;
추가로 margin, padding 속성 부여할 때는 
$t-spacing-xx 토큰을 사용하면 좋을 것 같습니다.

2024-01-30 09:13 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +                padding: 16px 10px 21px 16px;
spacing 은 짝수 단위로 넣는게 일반적이고, 21px은 토큰이 없으니 디자이너와 확인 부탁드립니다.

2024-01-30 09:13 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +                font-weight: normal;
font-weight도 

@include typo-xxx 로 해주세요.

2024-01-30 09:14 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +                padding: 0 16px 0 0;
여기도 spacing 토큰이요

2024-01-30 09:15 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +                font-weight: normal;
@kkusaeng 관련된 내용 설명 부탁드립니다. 내일 회고때 이야기해도 괜찮습니다.

2024-01-30 09:15 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +        margin-inline-end: 8px;
이 속성을 써보지는 않았는데, 이게 굳이 필요한 상황인가요?

2024-01-30 09:17 UTC, kkusaeng commented on src/styles/component/guide/toast/TToast.scss
> +                font-weight: normal;
넵

2024-01-30 09:18 UTC, Siyeop requested changes
toastify 옵션까지 찾아서 스타일 오버라이드 해주신 것 좋습니다.
css 강좌에 없는 개념까지 익히기 힘들었을 텐데 잘하셨네요.

다만 토큰에 대한 이해가 조금 더 필요한 것 같아서,
이 부분은 @kkusaeng 님이 설명 한번 더 해주시면 좋겠습니다.

2024-01-31 00:46 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +        margin-inline-end: 8px;
기존에 Toastify에서 icon에 margin을 줄 때 사용하고 있는 속성입니다. 해당 속성 기본 값이 10이고, 저희가 반영해야 하는 margin 값이 8이어서 해당 속성을 오버라이드 했습니다.

2024-01-31 00:59 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +            top: 4em;
spacing 토큰 사용해서 수정하였습니다.

2024-01-31 00:59 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +                font-weight: normal;
ThemeToken 내용 설명 듣고 반영했습니다.

2024-01-31 00:59 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +                padding: 0 16px 0 0;
spacing 토큰 반영했습니다

2024-01-31 01:03 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +                padding: 16px 10px 21px 16px;
spacing에 ThemeToken 반영했습니다. 21px은 padding 16px + absolute로 처리된 progress bar의 height 5px을 더해서 21px로 작성했었습니다. 해당 내용은 준희님 도움 받아서 progress bar의 height 길이를 변수로 만든 후, 21px을 calc로 계산하여 처리했습니다.

2024-01-31 04:24 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +        margin-inline-end: 8px;
그럼 이것도 스페이싱이니 토큰으로 변경 부탁드립니다.

2024-01-31 04:26 UTC, Siyeop commented on src/styles/component/guide/toast/TToast.scss
> +                padding: $t-spacing-16 $t-spacing-10 calc($t-spacing-16 + $t-toastify-progress-bar-height) $t-spacing-16;
👍 👍 👍

2024-01-31 04:28 UTC, Siyeop approved these changes
margin-inline-end 부분도 토큰으로 교체하는 것만 적용후 머지해주세요!
<img width="234" alt="image" src="https://github.com/openinfradev/tksui-components/assets/62166127/bfd46ac5-f843-461b-ade0-7b4922ab4d08">

2024-01-31 04:35 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +        margin-inline-end: 8px;
넵 spacing 토큰으로 변경했습니다.

2024-01-31 04:35 UTC, TaekRyeol commented on src/styles/component/guide/toast/TToast.scss
> +                padding: $t-spacing-16 $t-spacing-10 calc($t-spacing-16 + $t-toastify-progress-bar-height) $t-spacing-16;
👍

2024-01-31 04:36 UTC, merged